In [1]:
import numpy as np

In [2]:
np.zeros((10))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.ones((10))

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
my_list=[5,5,5,5,5,5,5,5,5,5]

In [15]:
np.array(my_list)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [16]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [17]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [21]:
np.random.randint(0,9,9).reshape(3,3)

array([[1, 0, 6],
       [0, 0, 1],
       [4, 5, 5]])

In [23]:
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
np.random.rand(3)

array([0.57059069, 0.94836983, 0.08485313])

In [29]:
np.random.randn(25)

array([ 1.38918095,  0.02068067,  0.44112745, -2.66732766, -0.96847983,
        1.70458005, -0.74586229,  1.19907162,  1.14019058,  0.45259405,
        0.76824525,  0.06522061,  0.84021263,  0.22043813,  0.67987516,
        1.0731238 , -1.55056593,  0.39671831, -0.35760746,  0.16534703,
       -0.3002945 ,  0.07500036, -1.77471357,  0.66698165,  0.77114428])

In [40]:
np.random.rand(1)

array([0.52207175])

In [55]:
np.arange(1,101).reshape(10,10)/10


array([[ 0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ],
       [ 1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ],
       [ 2.1,  2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ],
       [ 3.1,  3.2,  3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ],
       [ 4.1,  4.2,  4.3,  4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ],
       [ 5.1,  5.2,  5.3,  5.4,  5.5,  5.6,  5.7,  5.8,  5.9,  6. ],
       [ 6.1,  6.2,  6.3,  6.4,  6.5,  6.6,  6.7,  6.8,  6.9,  7. ],
       [ 7.1,  7.2,  7.3,  7.4,  7.5,  7.6,  7.7,  7.8,  7.9,  8. ],
       [ 8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,  8.8,  8.9,  9. ],
       [ 9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,  9.9, 10. ]])

In [36]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [59]:
mat= np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [60]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [61]:
mat[0:3,1:2] #.reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

In [62]:
mat[4]

array([21, 22, 23, 24, 25])

In [63]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [64]:
mat.sum()

325

In [66]:
mat.std()

7.211102550927978

In [51]:
#to find the sum of all the columns in mat
sum(mat)

array([55, 60, 65, 70, 75])

In [ ]:
960p6